/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.proyecto2.gui;

import javax.swing.JTextField;
import javax.swing.plaf.ColorUIResource;

import com.carlos.proyecto2.Casillas.*;
import com.carlos.proyecto2.EscrituraLecturaArchivos.EscrituraObjeto;
import com.carlos.proyecto2.Excepciones.ObjectNotSerializableExeption;
import com.carlos.proyecto2.Partida.Partida;
import com.carlos.proyecto2.Tablero.Tablero;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class EditarMapaJFrame extends javax.swing.JFrame {

    private MainFrame FramePrincipal;
    private Partida partidaCargada;
    private Tablero tableroCargado;
    private String directorioDeGuardado;
    private JTextField [] casillasGraficas;
    /**
     * Creates new form EditarMapaJInternalFrame
     */
    public EditarMapaJFrame(MainFrame FramePrincipal,Tablero tableroCargado,Partida partidaCargada,String directorioDeGuardado) {
        this.tableroCargado=tableroCargado;
        this.partidaCargada=partidaCargada;
        this.FramePrincipal = FramePrincipal;
        this.directorioDeGuardado=directorioDeGuardado;
        initComponents();
        this.casillasGraficas= creacionArreglo();
        this.setBounds(0, 0, 1000, 525);
        this.setLocationRelativeTo(null);
        pintarTablero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        casp21 = new javax.swing.JTextField();
        casp22 = new javax.swing.JTextField();
        casp23 = new javax.swing.JTextField();
        casp24 = new javax.swing.JTextField();
        casp10 = new javax.swing.JTextField();
        casp25 = new javax.swing.JTextField();
        casp26 = new javax.swing.JTextField();
        casp27 = new javax.swing.JTextField();
        casp28 = new javax.swing.JTextField();
        casp29 = new javax.swing.JTextField();
        casp30 = new javax.swing.JTextField();
        casp31 = new javax.swing.JTextField();
        casp32 = new javax.swing.JTextField();
        casp33 = new javax.swing.JTextField();
        casp35 = new javax.swing.JTextField();
        casp34 = new javax.swing.JTextField();
        casp36 = new javax.swing.JTextField();
        casp37 = new javax.swing.JTextField();
        casp38 = new javax.swing.JTextField();
        casp39 = new javax.swing.JTextField();
        casp40 = new javax.swing.JTextField();
        casp1 = new javax.swing.JTextField();
        casp2 = new javax.swing.JTextField();
        casp3 = new javax.swing.JTextField();
        casp5 = new javax.swing.JTextField();
        casp4 = new javax.swing.JTextField();
        casp6 = new javax.swing.JTextField();
        casp7 = new javax.swing.JTextField();
        casp8 = new javax.swing.JTextField();
        casp9 = new javax.swing.JTextField();
        casp11 = new javax.swing.JTextField();
        casp13 = new javax.swing.JTextField();
        casp14 = new javax.swing.JTextField();
        casp15 = new javax.swing.JTextField();
        casp20 = new javax.swing.JTextField();
        casp12 = new javax.swing.JTextField();
        casp16 = new javax.swing.JTextField();
        casp17 = new javax.swing.JTextField();
        casp18 = new javax.swing.JTextField();
        casp19 = new javax.swing.JTextField();
        CambiarjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombresCasillasjComboBox = new javax.swing.JComboBox<>();
        NombreCasillasjComboBox2 = new javax.swing.JComboBox<>();
        GuardarCambiosjButton = new javax.swing.JButton();
        SalirjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        casp21.setEditable(false);
        casp21.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp21.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp22.setEditable(false);
        casp22.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp22.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp23.setEditable(false);
        casp23.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp23.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp24.setEditable(false);
        casp24.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp24.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp10.setEditable(false);
        casp10.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp10.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp25.setEditable(false);
        casp25.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp25.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp26.setEditable(false);
        casp26.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp26.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp27.setEditable(false);
        casp27.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp27.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp28.setEditable(false);
        casp28.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp28.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp29.setEditable(false);
        casp29.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp29.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp30.setEditable(false);
        casp30.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp30.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp31.setEditable(false);
        casp31.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp31.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp32.setEditable(false);
        casp32.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp32.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp33.setEditable(false);
        casp33.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp33.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp35.setEditable(false);
        casp35.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp35.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp34.setEditable(false);
        casp34.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp34.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp36.setEditable(false);
        casp36.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp36.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp37.setEditable(false);
        casp37.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp37.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp38.setEditable(false);
        casp38.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp38.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp39.setEditable(false);
        casp39.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp39.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp40.setEditable(false);
        casp40.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp40.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp1.setEditable(false);
        casp1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp2.setEditable(false);
        casp2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp3.setEditable(false);
        casp3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp5.setEditable(false);
        casp5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp4.setEditable(false);
        casp4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp6.setEditable(false);
        casp6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp7.setEditable(false);
        casp7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp8.setEditable(false);
        casp8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp9.setEditable(false);
        casp9.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp11.setEditable(false);
        casp11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp11.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp13.setEditable(false);
        casp13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp13.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp14.setEditable(false);
        casp14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp14.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp15.setEditable(false);
        casp15.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp15.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp20.setEditable(false);
        casp20.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp20.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp12.setEditable(false);
        casp12.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp12.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp16.setEditable(false);
        casp16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp16.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp17.setEditable(false);
        casp17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp17.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp18.setEditable(false);
        casp18.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp18.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        casp19.setEditable(false);
        casp19.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        casp19.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        CambiarjButton.setText("Cambiar");
        CambiarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("-------->");

        jLabel2.setText("<--------");

        NombresCasillasjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inicio", "Peten", "Bolsa 1", "El Progreso", "SAT", "Aviateca", "Huehuetenango", "Cupon 1", "Quetzalteanngo", "Alta Verapaz", "Carcel", "Quiche", "Inde", "Izabal", "Chimaltenango", "Fegua", "Retalhuleu", "Bolsa 2", "Solola", "Escuintla", "Descanso Gratis", "San Marcos", "Cupon 2", "Chiquimula", "Baja Verapaz", "Flomerca", "Zacapa", "Totonicapan", "Empagua", "Guatemala", "Vaya a la carcel", "Santa Rosa", "Sacatepequez", "Bolsa 3", "Suchitepequez", "Microbus", "Cupon 3", "Jalapa", "Impuestos", "Jutiapa" }));

        NombreCasillasjComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inicio", "Peten", "Bolsa 1", "El Progreso", "SAT", "Aviateca", "Huehuetenango", "Cupon 1", "Quetzalteanngo", "Alta Verapaz", "Carcel", "Quiche", "Inde", "Izabal", "Chimaltenango", "Fegua", "Retalhuleu", "Bolsa 2", "Solola", "Escuintla", "Descanso Gratis", "San Marcos", "Cupon 2", "Chiquimula", "Baja Verapaz", "Flomerca", "Zacapa", "Totonicapan", "Empagua", "Guatemala", "Vaya a la carcel", "Santa Rosa", "Sacatepequez", "Bolsa 3", "Suchitepequez", "Microbus", "Cupon 3", "Jalapa", "Impuestos", "Jutiapa" }));

        GuardarCambiosjButton.setText("Guardar cambios");
        GuardarCambiosjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosjButtonActionPerformed(evt);
            }
        });

        SalirjButton.setText("Salir");
        SalirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(casp28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(casp25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(casp32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(700, 700, 700)
                        .addComponent(casp33, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casp18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casp14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casp17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casp16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casp15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(NombreCasillasjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CambiarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addComponent(NombresCasillasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casp35, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casp36, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casp37, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(casp34, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(casp38, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(700, 700, 700)
                        .addComponent(casp39, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(casp7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(casp40, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casp11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casp10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casp9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casp8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GuardarCambiosjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(casp4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casp3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casp2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(casp1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(SalirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casp21, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp29, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp30, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casp20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp32, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casp19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp33, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(casp14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(casp37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(casp34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(casp38, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreCasillasjComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CambiarjButton)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel2))
                            .addComponent(NombresCasillasjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casp13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp39, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casp12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp40, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(casp11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casp1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GuardarCambiosjButton)
                    .addComponent(SalirjButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarjButtonActionPerformed
        //extraenos el nombre de las casillas seleccionadas luego buscamos dichsa casilla por el nombre
        String nombreCasilla1 = (String)NombreCasillasjComboBox2.getSelectedItem();
        String nombreCasilla2 = (String)NombresCasillasjComboBox.getSelectedItem();
        //si al casillas de cambio tubieran el mismo nombre se lanza un error al usuario
        if(!nombreCasilla1.equals(nombreCasilla2)){
            //ser realiza el cambio de las casillas por medio del metodo que esta implemnetado en la clase lista de casillas
            Casillas casilla1 = this.tableroCargado.getCasillasDelTablero().buscarCasilla(nombreCasilla1);
            Casillas casilla2 = this.tableroCargado.getCasillasDelTablero().buscarCasilla(nombreCasilla2);
            this.tableroCargado.getCasillasDelTablero().switchDatos(casilla1, casilla2);
            pintarTablero();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "A seleccionado la misma casilla", "Error en cambio de casillas", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_CambiarjButtonActionPerformed

    private void SalirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirjButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Ah salido del editor si no guardo\nlos ultimos cambios se perderan\ndichos cambios", "Advertencia", JOptionPane.WARNING_MESSAGE);
        this.dispose();
        this.FramePrincipal.visualizarPrincipal();
    }//GEN-LAST:event_SalirjButtonActionPerformed

    private void GuardarCambiosjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosjButtonActionPerformed
        // se guardan los cambios y se sobre esciben los datos que se habian cargado
        EscrituraObjeto escribirObjeto = new EscrituraObjeto(this.directorioDeGuardado);
        try {
            this.partidaCargada.setTableroDeJuego(tableroCargado);
            escribirObjeto.WriteSerealizacion(this.tableroCargado ,this.tableroCargado.getNombreDelJuego(), this.tableroCargado.getNombreDelJuego());
            escribirObjeto.WriteSerealizacion(this.partidaCargada, this.partidaCargada.getNombreDeLaPartida(), this.partidaCargada.getNombreDeLaPartida());
            JOptionPane.showMessageDialog(this, "Se han guardado los cambios satisfacotriamente", "Completado", JOptionPane.INFORMATION_MESSAGE);
        } catch (ObjectNotSerializableExeption ex) {
            Logger.getLogger(EditarMapaJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(EditarMapaJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GuardarCambiosjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambiarjButton;
    private javax.swing.JButton GuardarCambiosjButton;
    private javax.swing.JComboBox<String> NombreCasillasjComboBox2;
    private javax.swing.JComboBox<String> NombresCasillasjComboBox;
    private javax.swing.JButton SalirjButton;
    private javax.swing.JTextField casp1;
    private javax.swing.JTextField casp10;
    private javax.swing.JTextField casp11;
    private javax.swing.JTextField casp12;
    private javax.swing.JTextField casp13;
    private javax.swing.JTextField casp14;
    private javax.swing.JTextField casp15;
    private javax.swing.JTextField casp16;
    private javax.swing.JTextField casp17;
    private javax.swing.JTextField casp18;
    private javax.swing.JTextField casp19;
    private javax.swing.JTextField casp2;
    private javax.swing.JTextField casp20;
    private javax.swing.JTextField casp21;
    private javax.swing.JTextField casp22;
    private javax.swing.JTextField casp23;
    private javax.swing.JTextField casp24;
    private javax.swing.JTextField casp25;
    private javax.swing.JTextField casp26;
    private javax.swing.JTextField casp27;
    private javax.swing.JTextField casp28;
    private javax.swing.JTextField casp29;
    private javax.swing.JTextField casp3;
    private javax.swing.JTextField casp30;
    private javax.swing.JTextField casp31;
    private javax.swing.JTextField casp32;
    private javax.swing.JTextField casp33;
    private javax.swing.JTextField casp34;
    private javax.swing.JTextField casp35;
    private javax.swing.JTextField casp36;
    private javax.swing.JTextField casp37;
    private javax.swing.JTextField casp38;
    private javax.swing.JTextField casp39;
    private javax.swing.JTextField casp4;
    private javax.swing.JTextField casp40;
    private javax.swing.JTextField casp5;
    private javax.swing.JTextField casp6;
    private javax.swing.JTextField casp7;
    private javax.swing.JTextField casp8;
    private javax.swing.JTextField casp9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
    
    public JTextField[] creacionArreglo(){
        /// se crea un arreglo que contia todas las JtextField para poderlas manera mas limpiamente al momento de escribir sobre ellas
      JTextField[] casillasGraficas = new JTextField[40];
      //SE GUARDAN TODOS LOS TEXTFIELD
      //
      casillasGraficas[0]=this.casp1;
    
      casillasGraficas[1]=this.casp2;
    
      casillasGraficas[2]=this.casp3;
    
      casillasGraficas[3]=this.casp4;
    
      casillasGraficas[4]=this.casp5;
    
      casillasGraficas[5]=this.casp6;
    
      casillasGraficas[6]=this.casp7;
    
      casillasGraficas[7]=this.casp8;
    
      casillasGraficas[8]=this.casp9;
    
      casillasGraficas[9]=this.casp10;
    
      casillasGraficas[10]=this.casp11;
    
      casillasGraficas[11]=this.casp12;
    
      casillasGraficas[12]=this.casp13;
    
      casillasGraficas[13]=this.casp14;
    
      casillasGraficas[14]=this.casp15;
    
      casillasGraficas[15]=this.casp16;
    
      casillasGraficas[16]=this.casp17;
    
      casillasGraficas[17]=this.casp18;
    
      casillasGraficas[18]=this.casp19;
    
      casillasGraficas[19]=this.casp20;
    
      casillasGraficas[20]=this.casp21;
    
      casillasGraficas[21]=this.casp22;
    
      casillasGraficas[22]=this.casp23;
    
      casillasGraficas[23]=this.casp24;
    
      casillasGraficas[24]=this.casp25;
    
      casillasGraficas[25]=this.casp26;
    
      casillasGraficas[26]=this.casp27;
    
      casillasGraficas[27]=this.casp28;
    
      casillasGraficas[28]=this.casp29;
    
      casillasGraficas[29]=this.casp30;
    
      casillasGraficas[30]=this.casp31;
    
      casillasGraficas[31]=this.casp32;
    
      casillasGraficas[32]=this.casp33;
    
      casillasGraficas[33]=this.casp34;
    
      casillasGraficas[34]=this.casp35;
    
      casillasGraficas[35]=this.casp36;
    
      casillasGraficas[36]=this.casp37;
    
      casillasGraficas[37]=this.casp38;
    
      casillasGraficas[38]=this.casp39;
    
      casillasGraficas[39]=this.casp40;

      for (int i = 0; i < casillasGraficas.length; i++) {
          casillasGraficas[i].setFont(new java.awt.Font("Ubuntu", 1, 9));
      }
      return casillasGraficas;
    }
    /**
     * METODO PARA PINTAR TABLERO
     */
    public void pintarTablero(){
        //se hace un ciclo y por medio de la clsificacon de instancias identidicamos y le asignamos un color por medio de otro metodo de esta clase
        Casillas casillasPintar = this.tableroCargado.getCasillasDelTablero().getRaiz();
        for (int i = 0; i < 40; i++) {
            this.casillasGraficas[i].setText(casillasPintar.getNombreCasilla());
            if(casillasPintar instanceof CasillaPropiedad)
            {
                this.casillasGraficas[i].setBackground(asignarColor(casillasPintar));
            }
            if(casillasPintar instanceof CasillaTrampaPagarMulta)
            {
                this.casillasGraficas[i].setBackground(asignarColor(casillasPintar));
            }
            if(casillasPintar instanceof CasillaTomaTarjeta)
            {
                this.casillasGraficas[i].setBackground(asignarColor(casillasPintar));
            }
            if(casillasPintar instanceof CasillaInicio)
            {
                this.casillasGraficas[i].setBackground(asignarColor(casillasPintar));
            }
            if(casillasPintar instanceof CasillaCarcel)
            {
                this.casillasGraficas[i].setBackground(asignarColor(casillasPintar));
            }
            if(casillasPintar instanceof CasillaNeutral)
            {
                this.casillasGraficas[i].setBackground(asignarColor(casillasPintar));
            }
            if(casillasPintar instanceof CasillaTrampaCambiarCasilla)
            {
                this.casillasGraficas[i].setBackground(asignarColor(casillasPintar));
            }
            casillasPintar = casillasPintar.getCasillaSiguiente();
        }
    }
    /**
     * Asigna el color de la casilla a pintar
     * @param casillaPintar casilla recibida
     * @return color en rgb
     */
    public ColorUIResource asignarColor(Casillas casillaPintar){
        
        ColorUIResource colorAsignado=new ColorUIResource(255, 255, 255);
        ///segun el tipo de instancia de casilla y el color asignado en ella se devuelve el color
        //LAS DEMAS CASILLAS SON COLORES YA PRESTABLECIDOS SEGUN LA INSTANCIA
        
        if(casillaPintar instanceof CasillaPropiedadLugar)
        {
            String colorAsignadoCasilla  = ((CasillaPropiedadLugar)casillaPintar).getGrupoPropiedad();
            if(colorAsignadoCasilla.equals("Rojo")){
                colorAsignado = new ColorUIResource(209, 62, 30);
            }
            if(colorAsignadoCasilla.equals("Amarillo")){
                colorAsignado = new ColorUIResource(244, 241, 26);
            }
            if(colorAsignadoCasilla.equals("Cafe")){
                colorAsignado = new ColorUIResource(165, 92, 92);
            }
            if(colorAsignadoCasilla.equals("Naranja")){
                colorAsignado = new ColorUIResource(228, 135, 37);
            }
            if(colorAsignadoCasilla.equals("Verde Claro")){
                colorAsignado = new ColorUIResource(102, 247, 142);
            }
            if(colorAsignadoCasilla.equals("Azul")){
                colorAsignado = new ColorUIResource(61, 111, 245);
            }
            if(colorAsignadoCasilla.equals("Rosa")){
                colorAsignado = new ColorUIResource(250, 131, 236);
            }
            if(colorAsignadoCasilla.equals("Verde")){
                colorAsignado = new ColorUIResource(69, 213, 43);
            }
        }
        if((casillaPintar instanceof CasillaPropiedadEstacion)||(casillaPintar instanceof CasillaPropiedadServicioBasico)){
            colorAsignado = new ColorUIResource(111, 196, 197);
        }
        if(casillaPintar instanceof CasillaTrampaPagarMulta){
            colorAsignado = new ColorUIResource(241, 110, 110);
        }
        if(casillaPintar instanceof CasillaTomaTarjeta)
        {
            String grupoTarjeta = ((CasillaTomaTarjeta)casillaPintar).getGrupoDeTarjeta();
            if(grupoTarjeta.equals("Cupon"))
            {
                colorAsignado = new ColorUIResource(241, 179, 110);
            }
            if(grupoTarjeta.equals("Bolsa"))
            {
                colorAsignado = new ColorUIResource(241, 221, 110);
            }
        }
        if(casillaPintar instanceof CasillaInicio)
        {
            colorAsignado=(new ColorUIResource(189, 109, 241));
        }
        if(casillaPintar instanceof CasillaCarcel)
        {
            colorAsignado=(new ColorUIResource(137, 133, 140));
        }
        if(casillaPintar instanceof CasillaNeutral)
        {
            colorAsignado=(new ColorUIResource(146, 189, 255));
        }
        if(casillaPintar instanceof CasillaTrampaCambiarCasilla)
        {
            colorAsignado=(new ColorUIResource(42, 132, 94));
        }
        return colorAsignado;
    }
}
