/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.proyecto2.gui;

import com.carlos.proyecto2.Jugador.Jugador;
import com.carlos.proyecto2.Partida.Partida;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class IngresoJugadoresJInternalFrame extends javax.swing.JInternalFrame {
    private MainFrame FramePrincipal;
    private Partida partida;
    private String directorioDeGuardado;
    private int numeroDeJugadores;
    private float cantidadInicialDinero;
    /**
     * Creates new form IngresoJugadoresJInternalFrame
     */
    public IngresoJugadoresJInternalFrame(String directorioDeGuardado,Partida partida,MainFrame FramePrincipal) {
        this.FramePrincipal=FramePrincipal;
        this.partida=partida;
        this.directorioDeGuardado=directorioDeGuardado;
        this.numeroDeJugadores=partida.getTableroDeJuego().getCantidadDeJugadores();
        this.cantidadInicialDinero=partida.getTableroDeJuego().getCantidadInicialDeDineroJugadores();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NombreJugadorjTextField = new javax.swing.JTextField();
        IngresarjButton = new javax.swing.JButton();
        SiguientejButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Nombre del Jugador");

        IngresarjButton.setText("Ingresar");
        IngresarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarjButtonActionPerformed(evt);
            }
        });

        SiguientejButton.setText("Siguiente");
        SiguientejButton.setEnabled(false);
        SiguientejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguientejButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("INGRESO DE JUGADORES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(IngresarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(SiguientejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(NombreJugadorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreJugadorjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IngresarjButton)
                    .addComponent(SiguientejButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarjButtonActionPerformed
        // VERIFICA SI LA CASILLA TIENE TEXTO
        if(!NombreJugadorjTextField.getText().equals("")){
            //VERIFICA SI EL NOBMBRE DEL JUGADOR YA AH SIDO INGRESADO
            if(!this.partida.getJugadoresDeLaPartida().buscarJugador(NombreJugadorjTextField.getText())){
                //CREA UN NUEVO JUGADOR SEGUN EL PARAMETRO DE INGRESO Y EN DINERO CONFIGURADO ENE LA PARTIDA
                Jugador temporal = new Jugador(NombreJugadorjTextField.getText(), this.cantidadInicialDinero);
                this.partida.getJugadoresDeLaPartida().agregar(temporal);
                this.numeroDeJugadores--;
                JOptionPane.showMessageDialog(this, "Jugador Ingresado exitosamente", "Ingresado", JOptionPane.INFORMATION_MESSAGE);
                if(this.numeroDeJugadores==0)
                {
                    JOptionPane.showMessageDialog(this, "Todos los jugadores han sido ingresados", "Terminado", JOptionPane.INFORMATION_MESSAGE);
                    IngresarjButton.setEnabled(false);
                    SiguientejButton.setEnabled(true);
                    NombreJugadorjTextField.setEnabled(false);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Nombre de jugador ya ingresado", "Error", JOptionPane.WARNING_MESSAGE);
                
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Nombre de jugador invalido", "Info", JOptionPane.ERROR_MESSAGE);
        }
        NombreJugadorjTextField.setText("");
        
    }//GEN-LAST:event_IngresarjButtonActionPerformed

    private void SiguientejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguientejButtonActionPerformed
        // TODO add your handling code here:
        FramePrincipal.configuracionDeTarjetasDelTablero(partida);
        this.doDefaultCloseAction();
    }//GEN-LAST:event_SiguientejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarjButton;
    private javax.swing.JTextField NombreJugadorjTextField;
    private javax.swing.JButton SiguientejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
