/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.carlos.proyecto2.gui;

import javax.swing.*;

import com.carlos.proyecto2.EscrituraLecturaArchivos.*;
import com.carlos.proyecto2.Excepciones.ObjectNotSerializableExeption;
import com.carlos.proyecto2.Partida.Partida;
import com.carlos.proyecto2.Tablero.Tablero;

import java.io.*;

/**
 *
 * @author benjamin
 */
public class NuevoJuegoJInternalFrame extends javax.swing.JInternalFrame {
    private String directorioDeGuardado;
    private MainFrame FramePrincial;
    //con este valor reconocemos el tipo de contructor con el cual se inicializo el formulario
    private int tipoconstructor=0;
    /** Creates new form NuevoJuegoJInternalFrame */
    public NuevoJuegoJInternalFrame(String directorioDeGuardado,MainFrame FramePrincipal) {
        this.tipoconstructor=1;
        initComponents();
        this.directorioDeGuardado = directorioDeGuardado;
        this.FramePrincial = FramePrincipal;
    }
    private Partida partidaCargada;
    private Tablero tableroCargado;
    public NuevoJuegoJInternalFrame(String directorioDeGuardado,MainFrame FramePrincipal,Partida partidaCargada,Tablero tableroCargado) {
        this.tipoconstructor=2;
        this.partidaCargada=partidaCargada;
        this.tableroCargado=tableroCargado; 
        initComponents();
        precargarDatos();
        this.directorioDeGuardado = directorioDeGuardado;
        this.FramePrincial = FramePrincipal;
        NombreJuegojTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NombreJuegojTextField = new javax.swing.JTextField();
        CantidadDineroInicialjTextField = new javax.swing.JTextField();
        CantidadJugadoresjComboBox = new javax.swing.JComboBox<>();
        CantidadDineroVueltaTextField = new javax.swing.JTextField();
        DadosjComboBox = new javax.swing.JComboBox<>();
        LimiteCasasjTextField = new javax.swing.JTextField();
        LimiteHotelesjTextField = new javax.swing.JTextField();
        PorcentajeHipotecajTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AceptarjButton = new javax.swing.JButton();
        CerrarjButton = new javax.swing.JButton();

        jLabel1.setText("Nombre del juego:");

        jLabel2.setText("Cantidad de jugadores:");

        jLabel3.setText("Cantidad inicial de dinero:");

        jLabel4.setText("Cantidad de dinero al pasar por inicio:");

        jLabel5.setText("Cantidad de dados a utilizar:");

        jLabel6.setText("Limite de Casas:");

        jLabel7.setText("Limite de hoteles");

        jLabel8.setText("Porcentaje de interes por hipoteca");

        CantidadJugadoresjComboBox
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));

        DadosjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel9.setText("%");

        AceptarjButton.setText("Aceptar");
        AceptarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarjButtonActionPerformed(evt);
            }
        });

        CerrarjButton.setText("Cerrar");
        CerrarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PorcentajeHipotecajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup().addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(DadosjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(
                                                layout.createSequentialGroup().addComponent(jLabel6).addGap(18, 18, 18)
                                                        .addComponent(LimiteCasasjTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 72,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(58, 58, 58).addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addComponent(LimiteHotelesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup().addContainerGap()
                                        .addComponent(CerrarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18,
                                                18)
                                        .addComponent(
                                                AceptarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup().addGap(10, 10, 10)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CantidadJugadoresjComboBox,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28).addComponent(jLabel3).addGap(18, 18, 18)
                                                .addComponent(CantidadDineroInicialjTextField,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 119,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup().addGap(12, 12, 12).addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup().addComponent(jLabel1)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(NombreJuegojTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 230,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup().addComponent(jLabel4)
                                                        .addGap(18, 18, 18).addComponent(CantidadDineroVueltaTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 149,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(32, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup().addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
                        .addComponent(NombreJuegojTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2)
                        .addComponent(CantidadJugadoresjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3).addComponent(CantidadDineroInicialjTextField,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel4)
                        .addComponent(CantidadDineroVueltaTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DadosjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(LimiteCasasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LimiteHotelesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel8)
                        .addComponent(PorcentajeHipotecajTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AceptarjButton).addComponent(CerrarjButton))
                .addContainerGap(18, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarjButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AceptarjButtonActionPerformed
        if(this.tipoconstructor==1){
            aceptarConstructor1();
        }
        if(this.tipoconstructor==2){
            aceptarConstructor2();
        }
    }                                              

    private void CerrarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarjButtonActionPerformed
        FramePrincial.habilitarPestanaJuego(true);
        this.doDefaultCloseAction();
        
    }//GEN-LAST:event_CerrarjButtonActionPerformed
    private void aceptarConstructor2(){
        int cantidadugadores=Integer.parseInt((String)CantidadJugadoresjComboBox.getSelectedItem());
        
        int cantidadDeJugadores = 0;
        float cantidadInicialDeDineroJugadores = 0;
        float cantidadDeDineroVuelta = 0;
        int limiteDeCasas = 0;
        int limiteDeHoteles = 0;
        float porcentajeInteresHipoteca = 0;
        int cantidadDeDados=0;
        if (validacionCamposDeTexto()) {
            //Conversion de datos asignados al tablero
            cantidadDeJugadores = Integer.parseInt((String)CantidadJugadoresjComboBox.getSelectedItem());
            cantidadInicialDeDineroJugadores = Float.parseFloat(CantidadDineroInicialjTextField.getText());
            cantidadDeDineroVuelta = Float.parseFloat(CantidadDineroVueltaTextField.getText());
            limiteDeCasas = Integer.parseInt(LimiteCasasjTextField.getText());
            limiteDeHoteles = Integer.parseInt(LimiteHotelesjTextField.getText());
            porcentajeInteresHipoteca = Float.parseFloat(PorcentajeHipotecajTextField.getText());
            cantidadDeDados=Integer.parseInt((String)DadosjComboBox.getSelectedItem());
            //
            if(cantidadugadores<this.tableroCargado.getCantidadDeJugadores()||cantidadugadores>this.tableroCargado.getCantidadDeJugadores())
            {
            EditorDeJugadoresJDialog editorJugadores = new EditorDeJugadoresJDialog(this.FramePrincial, true, this.partidaCargada.getJugadoresDeLaPartida(),this.tableroCargado,cantidadugadores,cantidadInicialDeDineroJugadores);
            editorJugadores.setVisible(true);
            }
            tableroCargado.setCantidadDeJugadores(cantidadDeJugadores);
            tableroCargado.setCantidadDeDatos(cantidadDeJugadores);
            tableroCargado.setCantidadInicialDeDineroJugadores(cantidadInicialDeDineroJugadores);
            tableroCargado.setCantidadDeDineroVuelta(cantidadDeDineroVuelta);
            tableroCargado.setLimiteDeCasas(limiteDeCasas);
            tableroCargado.setLimiteDeHoteles(limiteDeHoteles);
            tableroCargado.setPorcentajeInteresHipoteca(porcentajeInteresHipoteca);
            tableroCargado.setCantidadDeDatos(cantidadDeDados);
            
            this.partidaCargada.setTableroDeJuego(tableroCargado);
            
            try {
                EscrituraObjeto escribir = new EscrituraObjeto(this.directorioDeGuardado);
                escribir.WriteSerealizacion(this.partidaCargada,this.partidaCargada.getNombreDeLaPartida(),this.partidaCargada.getNombreDeLaPartida());
                escribir.WriteSerealizacion(tableroCargado,tableroCargado.getNombreDelJuego(),tableroCargado.getNombreDelJuego());
                JOptionPane.showMessageDialog(this, "Las configuraciones han sido efectuadas", "Info", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else{
                JOptionPane.showMessageDialog(this, "Campos de texto vacíos", "Error", JOptionPane.WARNING_MESSAGE);
        } 
        FramePrincial.habilitarPestanaJuego(true);
        this.doDefaultCloseAction();
    }
    private void aceptarConstructor1(){
        /**
         * DECLARACION DE VARIBLES DE ATRIBUTOS DEL JUEGO
         */
        String nombreDelJuego = "Prueba";
        int cantidadDeJugadores = 0;
        float cantidadInicialDeDineroJugadores = 0;
        float cantidadDeDineroVuelta = 0;
        int limiteDeCasas = 0;
        int limiteDeHoteles = 0;
        float porcentajeInteresHipoteca = 0;
        int cantidadDeDados=0;
        //FIN VARIABLES ATRIBUTOS DEL JUEGO
        //ASIGNACION DE VALORES
        nombreDelJuego=NombreJuegojTextField.getText();
        Partida partida;
        EscrituraObjeto escritura = new EscrituraObjeto(this.directorioDeGuardado);
        System.out.println(this.directorioDeGuardado);
        if (validacionCamposDeTexto()) {
            //Conversion de datos asignados al tablero
            cantidadDeJugadores = Integer.parseInt((String)CantidadJugadoresjComboBox.getSelectedItem());
            cantidadInicialDeDineroJugadores = Float.parseFloat(CantidadDineroInicialjTextField.getText());
            cantidadDeDineroVuelta = Float.parseFloat(CantidadDineroVueltaTextField.getText());
            limiteDeCasas = Integer.parseInt(LimiteCasasjTextField.getText());
            limiteDeHoteles = Integer.parseInt(LimiteHotelesjTextField.getText());
            porcentajeInteresHipoteca = Float.parseFloat(PorcentajeHipotecajTextField.getText());
            cantidadDeDados=Integer.parseInt((String)DadosjComboBox.getSelectedItem());
            //CREA UN PARTIDA DEL JUEGO Y REALIZA LA CREACION DEL SUBDIRECTORIO DEL JUEGO
            partida = new Partida(nombreDelJuego);
            partida.CrearTablero(cantidadDeJugadores, cantidadInicialDeDineroJugadores, cantidadDeDineroVuelta, limiteDeCasas, limiteDeHoteles, porcentajeInteresHipoteca,cantidadDeDados);
            partida.getTableroDeJuego().generarTablero();
            try {
                String indice = escritura.subCarpetaJuego(partida.getNombreDeLaPartida());
                if(!indice.equals("")){
                        partida.setNombreDeLaPartida(nombreDelJuego+indice);
                        partida.getTableroDeJuego().setNombreDelJuego(nombreDelJuego+indice);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Configuraciones generales asignadas", "Info", JOptionPane.INFORMATION_MESSAGE);
            FramePrincial.configuracionDeJugadoresDelJuego(partida);
            this.doDefaultCloseAction();
        }
        else{
                JOptionPane.showMessageDialog(this, "Campos de texto vacíos", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void precargarDatos()
    {
        NombreJuegojTextField.setText(this.tableroCargado.getNombreDelJuego());
        CantidadJugadoresjComboBox.setSelectedItem(String.valueOf(this.tableroCargado.getCantidadDeJugadores()));
        CantidadDineroInicialjTextField.setText(String.valueOf(this.tableroCargado.getCantidadInicialDeDineroJugadores()));
        CantidadDineroVueltaTextField.setText(String.valueOf(this.tableroCargado.getCantidadDeDineroVuelta()));
        LimiteCasasjTextField.setText(String.valueOf(this.tableroCargado.getLimiteDeCasas()));
        LimiteHotelesjTextField.setText(String.valueOf(this.tableroCargado.getLimiteDeHoteles()));
        PorcentajeHipotecajTextField.setText(String.valueOf(this.tableroCargado.getPorcentajeInteresHipoteca()));
        DadosjComboBox.setSelectedItem(String.valueOf(this.tableroCargado.getCantidadDeDatos()));
    }
    private boolean validacionCamposDeTexto(){
        boolean respuesta = false;
        boolean premisa1 = !NombreJuegojTextField.getText().equals("");
        boolean premisa2 = !CantidadDineroInicialjTextField.getText().equals("");
        boolean premisa3 = !CantidadDineroVueltaTextField.getText().equals("");
        boolean premisa4 = !LimiteCasasjTextField.getText().equals("");
        boolean premisa5 = !LimiteHotelesjTextField.getText().equals("");
        boolean premisa6 = !PorcentajeHipotecajTextField.getText().equals("");
        respuesta = premisa1 && premisa2 && premisa3 && premisa4 && premisa5 && premisa6;
        return respuesta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarjButton;
    private javax.swing.JTextField CantidadDineroInicialjTextField;
    private javax.swing.JTextField CantidadDineroVueltaTextField;
    private javax.swing.JComboBox<String> CantidadJugadoresjComboBox;
    private javax.swing.JButton CerrarjButton;
    private javax.swing.JComboBox<String> DadosjComboBox;
    private javax.swing.JTextField LimiteCasasjTextField;
    private javax.swing.JTextField LimiteHotelesjTextField;
    private javax.swing.JTextField NombreJuegojTextField;
    private javax.swing.JTextField PorcentajeHipotecajTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
